version: '3.8'
services:
  gateway:
    build: ./gateway
    image: shareit_gateway_image
    container_name: shareit_gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: shareit_sever_image
    container_name: shareit_sever
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"
    volumes:
          - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=share_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=root